// Playwright WebKit iPhone 13 煙霧測試。用法：BASE=http://localhost:3000 node test/smoke.mjs
import { webkit, devices } from 'playwright';
const BASE = process.env.BASE || 'http://localhost:3000';
const browser = await webkit.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
const fails = [];
const check = (name, ok) => { console.log((ok ? 'ok  ' : 'FAIL') + ' ' + name); if (!ok) fails.push(name); };

await page.goto(BASE + '/?d=999');
await page.waitForSelector('.line');
check('?d=999 falls back to today and renders', (await page.locator('.line').count()) === 5);
check('title rendered', (await page.locator('#titleZh').textContent()).trim().length > 0);
check('5 play buttons', (await page.locator('.line .play').count()) === 5);
check('text hidden by default', (await page.locator('.line.hide-en').count()) === 5);
await page.click('#showEn');
check('show english reveals', (await page.locator('.line.hide-en').count()) === 0);
check('zh still hidden', (await page.locator('.line.hide-zh').count()) === 5);
await page.click('#showZh');
check('show zh reveals', (await page.locator('.line.hide-zh').count()) === 0);
await page.click('#playAll');
await page.waitForTimeout(300);
check('playAll shows stop', (await page.locator('#playAll').textContent()).includes('停止'));
await page.click('#playAll');
await page.waitForTimeout(300);
check('second click stops', (await page.locator('#playAll').textContent()).includes('聽全部'));
await page.click('#doneBtn');
check('done button marks', (await page.locator('#doneBtn').textContent()).includes('已完成'));
check('stats show 1 day', (await page.locator('#stats').textContent()).includes('已練 1 天'));
check('stamp shown', (await page.locator('#stamp.show').count()) === 1);
check('next badge goal shown', (await page.locator('#badges').textContent()).includes('七日'));
await page.evaluate(() => { navigator.canShare = undefined; });
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 10000 }), page.click('#shareBtn')]);
check('share card downloads png', dl.suggestedFilename().endsWith('.png'));
// ── 今日口說任務 ──
const t = async sel => (await page.locator(sel).textContent()).trim();
await page.goto(BASE + '/?d=42'); await page.waitForSelector('.line');
await page.click('#missionBtn');
check('mission panel replaces lines', await page.locator('#mission').isVisible() && !(await page.locator('#lines').isVisible()) && !(await page.locator('#quizBtn').isVisible()));
check('stage 1 shows text + gloss', (await page.locator('#mission .m-text:not(.masked)').count()) === 1 && (await page.locator('#mission .m-zh').count()) === 1);
await page.click('.m-manual', { timeout: 8000 }); await page.click('.m-manual', { timeout: 8000 });
check('two reps counted, rotating lines', (await t('.m-count')).includes('總進度 2 / 100') && (await t('.m-count')).includes('第 3 句'));
await page.click('#missionBtn');
await page.evaluate(() => localStorage.setItem('dq365.mission', JSON.stringify({ 42: { stage: 4, k: 5, n: 4, done: false, t: new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Taipei' }).format(new Date()) } })));
await page.reload(); await page.waitForSelector('.line');
await page.click('#missionBtn');
check('stage 4 masks text, no replay', (await page.locator('#mission .m-text.masked').count()) === 1 && (await page.locator('#mission .m-hear').count()) === 0);
await page.click('.m-tip'); await page.click('.m-tip');
check('stage 4 hint shows gloss + first chars', (await page.locator('#mission .m-hint').textContent()).includes('…'));
await page.click('.m-manual');
check('self-check reveals text', (await page.locator('#mission .m-text.masked').count()) === 0 && (await page.locator('.m-ok').count()) === 1);
await page.click('.m-again');
check('retry does not count', (await t('.m-count')).includes('總進度 99 /'));
await page.click('.m-manual'); await page.click('.m-ok', { timeout: 8000 });
await page.waitForSelector('.m-done', { timeout: 5000 });
check('mission complete badge + seal', (await page.locator('.m-seal').count()) === 1);
await page.click('#missionBtn');
check('mission completes the lesson', (await t('#doneBtn')).includes('已完成') && (await page.locator('#stampSay.show').count()) === 1);
await page.goto(BASE + '/?d=46&mission=lite'); await page.waitForSelector('.line');
await page.click('#missionBtn');
check('?mission=lite starts lite (30, 3 stages)', (await t('.m-count')).includes('/ 30') && (await page.locator('.m-stages li').count()) === 3);
await page.click('#missionBtn');
check('quiz still opens after mission', await (async () => { await page.click('#quizBtn'); const ok = await page.locator('#quiz').isVisible(); await page.click('#quizBtn'); return ok; })());
await page.goto(BASE + '/?d=42');
await page.waitForSelector('.line');
check('?d=42 label', (await page.locator('#dayLabel').textContent()).includes('第 42 天'));
await page.goto(BASE + '/archive.html');
await page.waitForSelector('.grid a');
check('archive lists 365', (await page.locator('.grid a').count()) === 365);
check('archive hides unowned titles', (await page.locator('.grid a:not(.is-done) b', { hasText: '？？？' }).count()) === 363);
check('archive shows collected count', (await page.locator('#collected').textContent()).includes('2 / 365'));
await page.evaluate(async () => {
  const { taipeiDateKey, shiftDateKey } = await import('/js/day.js');
  const t = taipeiDateKey();
  localStorage.setItem('dq365.done', JSON.stringify(Array.from({ length: 7 }, (_, i) => shiftDateKey(t, -8 + i))));
});
await page.goto(BASE + '/'); await page.waitForSelector('.line');
check('old-format log + freeze keeps streak', (await page.locator('#stats').textContent()).includes('連續 7 天') && (await page.locator('#missed').textContent()).includes('保護卡'));
await browser.close();
if (fails.length) { console.error('FAILED:', fails); process.exit(1); }
console.log('smoke ok');
